version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: ./cookbook/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file: ./cookbook/.env
    ports:
      - 8000:8000
    volumes:
      - ../data:/app/data
    depends_on:
      - db
    restart: always
